DOMAIN = "vmc"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_SLAVE_ID = "slave_id"

SENSOR_TYPES = {
    "velocita_selezionata": {
        "name": "VMC Velocità Selezionata",
        "icon": "mdi:speedometer",
        "unit": None,
        "device_class": None,
        "address": 0,
        "data_type": "uint16",
    },
    "velocita_attiva": {
        "name": "VMC Velocità Attiva",
        "icon": "mdi:fan",
        "unit": None,
        "device_class": None,
        "address": 1,
        "data_type": "uint16",
    },
    "gest_ventilazione": {
        "name": "VMC Gestione Ventilazione",
        "icon": "mdi:air-filter",
        "unit": None,
        "device_class": None,
        "address": 2,
        "data_type": "uint16",
    },
    "gest_deumidifica": {
        "name": "VMC Gestione Deumidifica",
        "icon": "mdi:water-percent",
        "unit": None,
        "device_class": None,
        "address": 3,
        "data_type": "uint16",
    },
    "gest_integrazione": {
        "name": "VMC Gestione Integrazione",
        "icon": "mdi:heat-wave",
        "unit": None,
        "device_class": None,
        "address": 4,
        "data_type": "uint16",
    },
    "gest_ricircolo": {
        "name": "VMC Gestione Ricircolo",
        "icon": "mdi:sync",
        "unit": None,
        "device_class": None,
        "address": 5,
        "data_type": "uint16",
    },
    "modalita_attiva": {
        "name": "VMC Modalità Attiva",
        "icon": "mdi:air-conditioner",
        "unit": None,
        "device_class": None,
        "address": 6,
        "data_type": "uint16",
    },
    "gest_estate_inverno": {
        "name": "VMC Gestione Estate/Inverno",
        "icon": "mdi:sun-snowflake",
        "unit": None,
        "device_class": None,
        "address": 7,
        "data_type": "uint16",
    },
    "modalita_gestione": {
        "name": "VMC Modalità Gestione",
        "icon": "mdi:cog",
        "unit": None,
        "device_class": None,
        "address": 8,
        "data_type": "uint16",
    },
    "allarme_attivo": {
        "name": "VMC Allarme Attivo",
        "icon": "mdi:alarm-light",
        "unit": None,
        "device_class": None,
        "address": 10,
        "data_type": "uint16",
    },
    "codice_evento": {
        "name": "VMC Codice Evento",
        "icon": "mdi:information",
        "unit": None,
        "device_class": None,
        "address": 12,
        "data_type": "uint16",
    },
    "temp_immissione": {
        "name": "VMC Temperatura Immissione",
        "icon": "mdi:thermometer",
        "unit": "°C",
        "device_class": "temperature",
        "address": 26,
        "data_type": "float32",
    },
    "temp_rinnovo": {
        "name": "VMC Temperatura Rinnovo",
        "icon": "mdi:thermometer",
        "unit": "°C",
        "device_class": "temperature",
        "address": 27,
        "data_type": "float32",
    },
    "temp_ripresa": {
        "name": "VMC Temperatura Ripresa",
        "icon": "mdi:thermometer",
        "unit": "°C",
        "device_class": "temperature",
        "address": 28,
        "data_type": "float32",
    },
}

MODALITA_MAP = {
    0: "OFF",
    1: "Ventilazione",
    2: "Deumidifica",
    3: "Integrazione",
    4: "Deum+Integ",
    5: "Ricircolo",
    6: "Vent+Deum",
    7: "Vent+Integ",
    8: "Vent+Deu+Int",
    9: "Vent+Ricircolo",
    10: "Manutenzione",
    11: "Stand-By",
    12: "Deum STBY",
    13: "Integ STBY",
    14: "Deum+Integ STBY",
    15: "Vent+Deum STBY",
    16: "Vent+Integ STBY",
    17: "Vent+Deu+Int STBY",
}

VELOCITA_MAP = {
    0: "OFF",
    1: "Vel1",
    2: "Vel2",
    3: "Vel3",
    4: "Auto1",
    5: "Auto2",
}
